### PR TITLE
fix: reinstall broken packages in the store

### LINKED ISSUE #462: pnpm leaves broken packages in the store after crash
### Code to reproduce the issue:

Run an install that will fail.

### Expected behavior:

No half-installed packages will be added to the store

### Actual behavior:

All packages are being written to the store immediately and when there's a crash they are left there broken. Next installation will try to reuse them and will fail.

### PR DESCRIPTION
**Pull request by zkochan**
Close #462

### CODE REVIEW

File: test/install.ts [hunk 1]
```diff
@@ -719,3 +719,18 @@ test('should throw error when trying to install using a different store then the
 test('should not throw error if using a different store after all the packages were uninstalled', async function(t) {
   // TODO: implement
 })
+
+test('should reinstall package to the store if it is not in the store.yml', async function (t) {
```
Comment (iamstarkov) [inline test/install.ts:723]: 👏
