### PR TITLE
Fix issue with installing nested scoped packages

### LINKED ISSUE #219: Scoped packages
Hello, how difficult would it be to add support for scoped packages? For example: @kadira/storybook

### PR DESCRIPTION
**Pull request by zkochan**
When a dependency is dependent on a scoped package, there is an error during installation. I was able to reproduce it via a test and then fix it.

close #219

### CODE REVIEW

**Comment by rexxars** [comment]
:clap: Great work!
Super keen on seeing this merged.

File: lib/install.js [hunk 1]
```diff
@@ -248,10 +248,14 @@ function symlinkSelf (target, pkg, depth) {
...
       .then(_ => symlink(
         join('..', '_'),
-        join(target, 'node_modules', pkg.name)))
+        join(target, 'node_modules', escapeName(pkg.name))))
   }
 }
 
+function escapeName (name) {
+  return name && name.replace('/', '%2f')
+}
```
Comment (rstacruz) [inline lib/install.js:257]: ohh, of course
